### ISSUE TITLE
Change debug messages in verbose to use log crate

### ISSUE THREAD

**Issue by jamesmcm** [jamesmcm/s3rename#2]
Use log crate for debug messages, so we can add timestamps.

Also use log crate for standard messages (i.e. those filtered in quiet mode).

**Comment by Celeo** [comment]
Easy enough to do. This is a binary, so you'll need a log outputter as well. Common options are env_logger, pretty_env_logger, fern, log4s, and others. Any preference?

**Comment by jamesmcm** [comment]
I've used pretty_env_logger before but I'm happy with any of them really.

**Comment by jamesmcm** [comment]
Works great thanks! :slightly_smiling_face:
