### ISSUE TITLE
Try to get AWS region from local environment if not provided

### ISSUE THREAD

**Issue by jamesmcm** [jamesmcm/s3rename#9]
Get the AWS environment from the local environment (e.g. `~/.aws/config` ) if it is not provided, Rusoto probably has a function for this.

Only really matters for the initial get_bucket_location request, as after that we want to use region of the bucket itself.

**Comment by davidmaceachern** [comment]
Duplicate of #18 .

**Comment by jamesmcm** [comment]
Thanks for the help!
